[package]
name = "viz-js-rs-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
viz-js = { path = "../.." }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = {version = "0.3.64", features = ["Document", "Window", "HtmlElement"]}