name: Build

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: cgt-rs build

    strategy:
      matrix:
        os: ["ubuntu-latest"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: Build
        run: cargo build --release --all

      - name: Test
        run: cargo test --all
